In [1]:
from metrics import num_swapped_pairs, compute_gain, dcg, ndcg, precision_at_k, reciprocal_rank, p_found, average_precision
import torch

In [2]:
y_true = torch.rand(3)
y_pred = torch.rand(3)

In [ ]:
y_pred

tensor([0.3584, 0.8787, 0.3723])

In [4]:
reciprocal_rank(torch.Tensor([0, 0, 1]), y_pred)

0.5

In [3]:
dcg(y_true, y_pred, 'const')

1.2087531298846528

In [6]:
y_pred = torch.rand(3)
y_pred

tensor([0.3140, 0.7849, 0.9050])

In [7]:
_, indices = torch.sort(y_pred, descending=True)
indices

tensor([2, 1, 0])

In [9]:
y_true = torch.Tensor([0, 1, 0])
y_true # 1

tensor([0., 1., 0.])

In [11]:
ys_true_sorted = y_true[indices]
ys_true_sorted

tensor([0., 1., 0.])

In [12]:
(ys_true_sorted == 1)

tensor([False,  True, False])

In [14]:
(ys_true_sorted == 1).nonzero(as_tuple=True)[0].item()

1

In [15]:
(ys_true_sorted == 1).nonzero(as_tuple=True)[0].item() + 1

2

In [14]:
y_pred = torch.Tensor([0.7841, 0.4637, 0.9349, 0.2557, 0.0104, 0.5263, 0.2438, 0.5560, 0.3493, 0.5722])
y_bin_true = torch.Tensor([0., 0., 0., 0., 1., 0., 0., 1., 0., 0.])

In [15]:
p_found(y_bin_true, y_pred)

0.6141249999999999